# dont forget to update this number according to following contents
number_of_detectors: 2

sensor_0: # the names are fixed, just the number changes

  name: 'dummy'

  photon_flux: 0            # [photons/s], whole number
  simulate_background: true   # should we simulation radiation background?
  n_images: 20                # how many images of radiation background do we have?

  defaults:
    exposure: 1.0             # [seconds]

sensor_1: # the names are fixed, just the number changes

  name: 'dummy'

  photon_flux: 0            # [photons/s], whole number
  simulate_background: true   # should we simulation radiation background?
  n_images: 20                # how many images of radiation background do we have?

  defaults:
    exposure: 1.0             # [seconds]
